title: Shimataiyaki
description: 個人開発記録
baseurl: ""
url: "https://shimataiyaki.github.io"

shinkai:
  title: Shinkai
  subtitle: Make Your Team More Systematic
  github: https://github.com/shimataiyaki/shinkai
